version: '3'
services:
  mongodb:
    image: mongo
    deploy:
      replicas: 1
    ports:
      - 27017:27017
    volumes:
      - /home/hailson.junior/volumes/mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongo123
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    deploy:
      replicas: 1
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongo123
    networks:
      - mongo-network
    depends_on:
      - mongodb

networks:
  mongo-network:
